USE AGROFY;

CREATE TABLE FARMER_REG(FIRST_NAME VARCHAR(50),LAST_NAME VARCHAR(50),GENDER VARCHAR(6),EMAIL VARCHAR(150),USER_ROLE VARCHAR(20),NIC VARCHAR(12),MOBILE INT(11),ADDRESS_ VARCHAR(150),LAND_ADDRESS VARCHAR(150) ,LAND_HECTARES INT(3),TYPE_OF_CROP VARCHAR(100),NO_OF_EMPLOYEES INT(3), PROFILE_IMG BLOB ,USER_NAME VARCHAR(12),PASS VARCHAR(12)  );

CREATE TABLE BUSINESS_REG(FIRST_NAME VARCHAR(50),LAST_NAME VARCHAR(50),GENDER VARCHAR(6),EMAIL VARCHAR(150),USER_ROLE VARCHAR(20),NIC VARCHAR(12),MOBILE INT(11),ADDRESS_ VARCHAR(150),BUSINESS_NAME VARCHAR(150) ,BUSINESS_REG_NO VARCHAR(15),TYPE_OF_BUSINESS VARCHAR(50),ADDRESS_WORK_PLACE VARCHAR(100), PROFILE_IMG BLOB ,USER_NAME VARCHAR(12),PASS VARCHAR(12));

CREATE TABLE COMPOST_SUP_REG(FIRST_NAME VARCHAR(50),LAST_NAME VARCHAR(50),GENDER VARCHAR(6),EMAIL VARCHAR(150),USER_ROLE VARCHAR(20),NIC VARCHAR(12),MOBILE INT(11),ADDRESS_ VARCHAR(150),WORK_ADDRESS VARCHAR(150) ,TYPE_OF_COMPOST VARCHAR(50),BUSINESS_NAME VARCHAR(50), NO_OF_EMPLOYEES INT(3), PROFILE_IMG BLOB ,USER_NAME VARCHAR(12),PASS VARCHAR(12)  );
